- hosts: visioncpu
  user: "mbaradad"
  tasks:
    - name: "execute my script"
      script: matlab_datasets.sh

# f is the number of forks! important to put as max as needed for true parallelism so that the master does not wait for
# completion of some of the slaves.
#| => # kill each hour, some matlab instances seem to hang
      # watch -n 3600 "ansible-playbook -i visioncpu ansible_run_distributed_matlab_script/matlab_datasets.yml -f 50"