- hosts: visiongpu
  user: "mbaradad"
  tasks:
    - name: "execute my script"
      script: generate_images_per_fragment_sweep_multiclass.sh

# f is the number of forks! important to put as max as needed for true parallelism so that the master does not wait for
# completion of some of the slaves.
#| => ansible-playbook -i visiongpu ansible_run_distributed_python_script/generate_images_per_fragment_sweep_multiclass.yml -f 50